### ISSUE TITLE
No source for reproducing x_train.npy,y_train.npy and valid.npy

### ISSUE THREAD

**Issue by ssemyonov-quantori** [ShahinSHH/COVID-CAPS#2]
Hello,

1) I managed to get pretrained data and use it as described in your repository
2) I inspected your github repository and process the data according to the source of COVID-NET, but the output is data/test and data/train, however in your code you use
x_train= np.load("x_train.npy")
y_train= np.load("y_train.npy")>=3
x_valid= np.load("x_valid.npy")

I did my best, but couldn't find a way to transform the output of COVID-NET into the npy arrays.
Please help me to clarify it.

Thanks.

**Comment by ssemyonov-quantori** [comment]
@ShahinSHH 
Please check, I sent an email to Arash but it seems to be a tehnical issue rather then research one

**Comment by ShahinSHH** [comment]
Hello,

It was supposed to find the right code in COVID-NET repository. However, I added preprocess.py - train_split_v3.txt - valid_split_v3.txt - test_split_v3.txt to the repository. Please follow the steps below: 
1. Create ./data/train - ./data/test - ./data/valid directories.
2. Run preprocess.py to split the data and export .npy files.
3. This code works with an updated version of data COVID-NET data (check COVID-NET for the new updates) and you need to use y_train= np.load("y_train.npy")>=2 instead of 3

!! NOTE: COVID-NET dataset has been updated a couple of times so far, so if you're working with the latest version, use the latest "train_COVIDx3.txt", "test_COVIDx3.txt" in their repository and follow their guidelines to prepare the train/test data and .txt files. Then you can split train data  into train/valid and create (train_split_v3.txt - valid_split_v3.txt - test_split_v3.txt) and use preprocess.py to save them in .npy format.

**Comment by ssemyonov-quantori** [comment]
@ShahinSHH 
Thanks for the feedback.

How do you exactly create the validate dataset?
create_COVIDx_v3.ipynb from COVID-NET repo only creates  
train_split_v3 and test_split_v3

**Comment by ShahinSHH** [comment]
Please use the following code follow directions below:

1. This takes "train_split_v3.txt" and images in the ./data/train created by COVID-NET as inputs. Splits train data into training/validation. It saves the images into "training", "validation" folders and creates "training_split_v3.txt" and "validation_split_v3.txt"
2. Create ./data/training and ./data/validation directories yourself. Rename created "training_split_v3.txt" and "validation_split_v3.txt" to "train_split_v3.txt" and "valid_split_v3.txt" before using them in "preprocess.py"

**Code:

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd #import and manage datasets
import os
from sklearn.model_selection import train_test_split
import cv2

def _process_csv_file(file):
    with open(file, 'r') as fr:
        files = fr.readlines()
    return files

#importing train data
train_full_data = _process_csv_file('train_split_v3.txt')

train_data, valid_data = train_test_split(train_full_data, test_size = 0.1, random_state = 0)

for i in train_data:  
    image_name = i.split()[1]
    pixel_array_numpy = cv2.imread(os.path.join('data', 'train', image_name))
    cv2.imwrite(os.path.join('data', 'training', image_name), pixel_array_numpy)
        
for i in valid_data:  
    image_name = i.split()[1]
    pixel_array_numpy = cv2.imread(os.path.join('data', 'train', image_name))
    cv2.imwrite(os.path.join('data', 'validation', image_name), pixel_array_numpy)


training_file = open("training_split_v3.txt","a") 
for s in train_data:

    training_file.write(s)

training_file.close()

validation_file = open("validation_split_v3.txt", "a")
for s in valid_data:

    validation_file.write(s)

validation_file.close()

**Comment by ssemyonov-quantori** [comment]
@ShahinSHH 
Thanks, now it is done.
